### ISSUE TITLE
Cannot find module '.\src\lzma_worker.js'

### ISSUE THREAD

**Issue by MatteoGioioso** [LZMA-JS/LZMA-JS#76]
I am trying to use this module with React and create-react-app, but looks like is not working. And I think it is failing at the import phase. I have tried common.js as well but same result.

### method 1
As suggested here: https://github.com/LZMA-JS/LZMA-JS#how-to-use
I have copied and pasted `lzma_worker.js'` in the same folder I am importing it.

```
import LZMA from 'lzma';
const compressedBody = LZMA.compress(stringBody);
const lzma = new LZMA('./lzma_worker.js');
const compressedBody = lzma.compress(stringBody);
```

### method 2

As suggested here: https://github.com/LZMA-JS/LZMA-JS#but-i-dont-want-to-use-web-workers

I am importing the script in the public folder, after I have copied there

```
<script src="%PUBLIC_URL%/lzma_worker.js"></script>
```

Then importing it in my code

```
import LZMA from 'lzma';
const compressedBody = lzma.compress(stringBody);

```

----

React: ` "react": "^16.13.1"`
React script: `"react-scripts": "^3.4.1"`
Node: `8.10`

**Comment by marozartsem9** [comment]
@MatteoGioioso , after installing package by npm or yarn you can import it like:

`import 'lzma/src/lzma_worker';`

it will create global variable `LZMA` which you need.

**Comment by MatteoGioioso** [comment]
@marozartsem9 ok, solved thanks!
